services:
  db:
    image: postgres:18
    restart: always
    container_name: postgres_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    container_name: go_app
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "4880:8080"
    volumes:
      - ./templates:/usr/app/templates       
      - ./config:/usr/app/config             

volumes:
  postgres_data:
